---
title: "eda"
author: "nz2333"
date: "10/20/2021"
output: github_document
---
```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.height = 0.6, 
  out.width = "90%"
)
```

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## group_by
```{r}
weather_df %>%
  group_by(name)
```

## count some things
```{r}
weather_df %>%
  group_by(month) %>%
  summarize(n_obs = n())

weather_df %>%
  count(name)
```

vs. 
```{r}
weather_df %>%
  pull(name)%>%
  table()
```

```{r}
weather_df %>%
  janitor::tabyl(month, name)
```

## More general summaries

Count, take means, look at SDs
```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n_obs = n(), 
    mean_tmax = mean(tmax, na.rm = TRUE), 
    sd_tmax = sd(tmax, na.rm  = TRUE), 
    median_tmax = median(tmax, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```


Formatting table outputs
```{r}
weather_df %>%
  group_by(name)%>%
  summarize(
    n_obs = n(), 
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>%
  knitr::kable(digits = 2)
```

