---
title: "viz_eda_part2"
author: "nz2333"
date: "10/20/2021"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```

load weather data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) +
  geom_point(alpha = 0.5)
```

## labels
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp",
    y = "Max daily temp", 
    caption = "Data from rnooa package; tempratures in 2017"
  )
```

##Scales
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp",
    y = "Max daily temp", 
    caption = "Data from rnooa package; tempratures in 2017"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15 C", "0", "15")
  ) +
  scale_y_continuous(
    trans = "log",
    position = "right"
  )
```

Look at colors:
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp",
    y = "Max daily temp", 
    caption = "Data from rnooa package; tempratures in 2017"
  ) +
  scale_color_hue(
    name = "Location", 
    h = c(100, 300))
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp",
    y = "Max daily temp", 
    caption = "Data from rnooa package; tempratures in 2017"
  ) +
  viridis::scale_color_viridis(name = "Location",
                               discrete = TRUE )
```

## Themes

Shift the legend
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp",
    y = "Max daily temp", 
    caption = "Data from rnooa package; tempratures in 2017"
  ) +
  viridis::scale_color_viridis(name = "Location",
                               discrete = TRUE ) +
  theme(legend.position = "bottom")
  
```
 Change the overall theme
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color= name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp",
    y = "Max daily temp", 
    caption = "Data from rnooa package; tempratures in 2017"
  ) +
  viridis::scale_color_viridis(name = "Location",
                               discrete = TRUE ) +
  theme_minimal() +
  theme(legend.position = "bottom") 
```
^^must chaneg overall theme first, then do the legend



## setting options
```{r, eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 0.6, 
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom")
          
options(
  ggplot2.continuous/colour = "viridis", 
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_discrete_d
```
^ usually run this at the beginning


## data args in geom

```{r}
central_park = 
  weather_df %>%
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>%
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x= date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)
```

