---
title: "ggplot 1"
author: "nz2333"
date: "10/20/2021"
output: github_document
---
```{r}
library(tidyverse)
```

load in a datset
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Scatterplot

tmax vs tmin

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()
```

you can save ggplots

```{r}
ggp_tamx_tmin = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()

ggp_tamx_tmin
```

## fancy it up

add color, lines, and other stuff?

```{r}
 weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```
^alpha: transparency level. 
smooth: adding the line
facet_grid: make it separate. 

## more scatter plot

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, size = prcp)) +
  geom_point(apha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

## use data manipulation as part of this

```{r}
weather_df %>%
  filter(name == "CentralPark_NY") %>%
  mutate(
    tmax = tmax * (9/5) + 32, 
    tmin = tmin * (9/5) + 32
  ) %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

## stacking geoms
which geoms do you want?

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax ,color = name)) +
  geom_smooth()
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```
^this shows how dense data is 


